### ISSUE TITLE
Azure load balanced issues

### ISSUE THREAD

**Issue by alexroessler** [avisra/SiteWarmup#2]
I am curious if this project has been tested recently warming up a Sitefinity site running as an Azure Web App using load-balancing.

I pulled the AzureScaledSiteWarmup branch.

I disabled the precompilation completely by commenting the 2 relevant lines in runner.ps1

I was able to get it to work running as a webjob on my web app after I added the line "azure config mode asm" before the "azure account import..." line in Runner.ps1

While the warm up is running it successfully queries the instance guids and tries to warm up the URLs from the sitemap. I had to change the $request.Timeout value in SiteWarmup.ps1 because the first page request never completed. I changed the value to 60000.

Checking my log*.csv files that are created I see this in the first instance's log:
...
"10/5/2017 12:57:12 AM","BAD","http://amwins-test-app.azurewebsites.net/about-us/newsroom/awards-recognition","60682 ms",
"10/5/2017 12:57:12 AM","BAD","http://amwins-test-app.azurewebsites.net/about-us/find-a-location","60137 ms",
"10/5/2017 12:57:13 AM","BAD","http://amwins-test-app.azurewebsites.net/about-us/find-a-location/us-locations","60588 ms",
"10/5/2017 12:57:13 AM","BAD","http://amwins-test-app.azurewebsites.net/about-us/find-a-location/global-locations","60280 ms",
"10/5/2017 12:57:13 AM","BAD","http://amwins-test-app.azurewebsites.net/find-a-contact","60684 ms",
"10/5/2017 12:57:14 AM","BAD","http://amwins-test-app.azurewebsites.net/find-a-contact/search","60762 ms",
"10/5/2017 12:57:16 AM","BAD","http://amwins-test-app.azurewebsites.net/about-us/leadership/board-of-directors","60981 ms",
"10/5/2017 12:57:16 AM","BAD","http://amwins-test-app.azurewebsites.net/products-services/property-casualty/professional-lines","60465 ms",
"10/5/2017 12:57:16 AM","BAD","http://amwins-test-app.azurewebsites.net/products-services/industries/public-entity","60821 ms",
"10/5/2017 12:58:08 AM","BAD","http://amwins-test-app.azurewebsites.net/products-services/industries","112044 ms",
"10/5/2017 12:58:08 AM","BAD","http://amwins-test-app.azurewebsites.net/products-services/underwriting-programs","111717 ms",
"10/5/2017 12:58:09 AM","BAD","http://amwins-test-app.azurewebsites.net/products-services/underwriting-programs/mga-specialty-programs","112232 ms",
"10/5/2017 12:58:10 AM","BAD","http://amwins-test-app.azurewebsites.net/prma","112747 ms",
"10/5/2017 12:58:12 AM","BAD","http://amwins-test-app.azurewebsites.net/about-prma","114356 ms",
"10/5/2017 12:58:12 AM","BAD","http://amwins-test-app.azurewebsites.net/products-services/industries/construction","114077 ms",
...

The next instance shows some requests that are OK and some that are bad:
"10/5/2017 1:12:35 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/industries/healthcare","86272 ms",
"10/5/2017 1:12:37 AM","OK","http://amwins-test-app.azurewebsites.net/premier","86831 ms",
"10/5/2017 1:12:38 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/group-benefits/retailers","87507 ms",
"10/5/2017 1:12:39 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/group-benefits/retailers/small-groups","88131 ms",
"10/5/2017 1:12:41 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/group-benefits/retailers/middle-market","85992 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/group-benefits/retailers/large-groups","85414 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/group-benefits/carriers","67078 ms",
"10/5/2017 1:12:43 AM","BAD","http://amwins-test-app.azurewebsites.net/products","113102 ms",
"10/5/2017 1:12:43 AM","BAD","http://amwins-test-app.azurewebsites.net/insights","111781 ms",
"10/5/2017 1:12:43 AM","BAD","http://amwins-test-app.azurewebsites.net/about-us/leadership","111309 ms",
"10/5/2017 1:12:43 AM","BAD","http://amwins-test-app.azurewebsites.net/about-us/partnerships","111027 ms",
"10/5/2017 1:12:43 AM","BAD","http://amwins-test-app.azurewebsites.net/about-us/culture","110621 ms",
...
"10/5/2017 1:12:43 AM","BAD","http://amwins-test-app.azurewebsites.net/about-us/newsroom/awards-recognition","108806 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/property-casualty","266 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/property-casualty/property","127 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/property-casualty/small-business","124 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/products-services/property-casualty/personal-lines","155 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/operating-company-pages/apu","138 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/operating-company-pages/woodus","78 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/operating-company-pages/atu","94 ms",
"10/5/2017 1:12:43 AM","OK","http://amwins-test-app.azurewebsites.net/operating-company-pages/spfm","94 ms",

Another thing is that I noticed the Kudu interface for the site becoming unresponsive at times during the warmup process. 

The site works normally when browsing, pages showing the ridiculous request times take 10 seconds for initial request and less than 1 second for subsequent requests. I confirmed that this is true for different instances by checking the value of the "ARRAffinity" cookie in chrome.

I would be very happy to get any thoughts on this. 

Thank you!

[output_log.txt](https://github.com/avisra/SiteWarmup/files/1357811/output_log.txt)

[log6ee994c87689c2b533d026108f3cda491ae8c5bb2c4d1347869cddd7c1773664.csv.txt](https://github.com/avisra/SiteWarmup/files/1357812/log6ee994c87689c2b533d026108f3cda491ae8c5bb2c4d1347869cddd7c1773664.csv.txt)
[logc12be142cb54f1feb18b0836921d58503836badeebf259f3f19c32d8bc0c474c.csv.txt](https://github.com/avisra/SiteWarmup/files/1357813/logc12be142cb54f1feb18b0836921d58503836badeebf259f3f19c32d8bc0c474c.csv.txt)

**Comment by avisra** [comment]
Alex,

I apologize for never having responded to this. The tool was tested with Azure App Services back when this branch was created. It looks like you are getting OK responses sometimes. But the long wait time makes me think that maybe you need configure the script to run less responses in parallel. This could be from using a really low tier app service plan (low CPU). Also, removing the precompiler will put a very large load on Azure during the warmup process. Try deploying the precompiled dlls before running the warmup.

Also - there is a warmup tool delivered out of the box with Sitefinity now (also developed by me). That should run great in azure environments :)

Chris
